loanapp/core/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
     path('terms/', views.terms, name='terms'),
    path('faq/', views.faq, name='faq'),
    path('privacy/', views.privacy, name='privacy'),
    path('business-loan/', views.business_loan, name='business_loan'),
    path('investment-loan/', views.investment_loan, name='investment_loan'),
    path('personal-loan/', views.personal_loan, name='personal_loan'),
    path('emergency-loan/', views.emergency_loan, name='emergency_loan'),
]

loanapp/loanapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import CustomDisable2FAView, CustomSetup2FAView, CustomTwoFactorLoginView

SESSION_COOKIE_SECURE = False  # for local dev
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('adminpanel/', include('adminpanel.urls', namespace='adminpanel')),
    path('', include('core.urls')),

    path('account/two_factor/disable/', CustomDisable2FAView.as_view(), name='two_factor:disable'),
    path('account/two_factor/setup/', CustomSetup2FAView.as_view(), name='two_factor:setup'),
    path('account/two_factor/', include('two_factor.urls', 'two_factor')),  # Modified line
    path('account/two_factor/login/', CustomTwoFactorLoginView.as_view(), name='two_factor:login'),

    # Allauth URLs
    # path('accounts/social/signup/', CustomSocialSignupView.as_view(), name='socialaccount_signup'),
    path('accounts/', include('allauth.urls')),
]

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = (core + profile + plugin_urlpatterns, 'two_factor')

loanapp/user/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from two_factor.views import LoginView
# from .views import CustomSocialSignupView


app_name = 'user'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('kyc/verify/', views.kyc_step_1, name='kyc_verify'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('repay/', views.repay, name='repay'),
    path('transactions/', views.transactions, name='transactions'),
    path('help/', views.help_center, name='help_center'),
    path('loan/apply/', views.loan_apply, name='loan_apply'),
    path('deposit/', views.deposit_view, name='deposit'),
    path('deposit/<int:pk>/', views.deposit_details_view, name='deposit_details'),
    path('kyc/', views.kyc_step_1, name='kyc_step_1'),
    path('kyc/identity/', views.kyc_step_2, name='kyc_step_2'),
    path('kyc/review/', views.kyc_step_3, name='kyc_step_3'),
    path('settings/', views.profile_settings, name='profile_settings'),
    path('notifications/', views.notifications, name='notifications'),
    path('register/', views.register, name='register'),

    path('login/', LoginView.as_view(), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dismiss-kyc-verified-alert/', views.dismiss_kyc_verified_alert, name='dismiss_kyc_verified_alert'),
    path('dismiss-twofa-alert/', views.dismiss_twofa_alert, name='dismiss_twofa_alert'),
    path('deposit/success/', views.deposit_success, name='deposit_success'),
    path('profile/', views.profile, name='profile'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='user/password_change.html'
    ), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='user/password_change_done.html'
    ), name='password_change_done'),

    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset.html'
    ), name='password_reset'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password/set/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_set.html',
        success_url='/user/login/'  # Redirect to login after setting password
    ), name='password_reset_confirm'),
    path('accounts/password/set/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_set_done.html'
    ), name='password_reset_complete'),

    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('test-disable/', views.test_disable, name='test_disable'),
    path('post-signup/', views.post_signup, name='post_signup'),

]

loanapp/core/models.py
from django.db import models

# Create your models here.

loanapp/core/views.py
from django.shortcuts import render
from django.urls import path
from . import views
from django.templatetags.static import static


def home(request):

    approved_logos = [
        {"name": "Boa", "url": static("assets/images/approved/bank-of-america.svg")},
        {"name": "chase", "url": static("assets/images/approved/chase.svg")},
        {"name": "chase", "url": static("assets/images/approved/logo_1.svg")},
        {"name": "chase", "url": static("assets/images/approved/logo_2.svg")},
        {"name": "chase", "url": static("assets/images/approved/logo_3.svg")},
        {"name": "chase", "url": static("assets/images/approved/logo_4.svg")},
        {"name": "chase", "url": static("assets/images/approved/logo_5.svg")},
        {"name": "chase", "url": static("assets/images/approved/td-bank-1.svg")},
        {"name": "chase", "url": static("assets/images/approved/citizens-bank-logo-1.svg")},
    ]

    return render(request, 'core/home.html', {"approved_logos": approved_logos})

def services(request):
    return render(request, 'core/services.html')



def contact(request):
    return render(request, 'core/contact.html')

def terms(request):
    return render(request, 'core/terms.html')


def faq(request):
    return render(request, 'core/faq.html')

def privacy(request):
    return render(request, 'core/privacy.html')

def business_loan(request):
    return render(request, 'core/businessloan.html')

def investment_loan(request):
    return render(request, 'core/investmentloan.html')

def personal_loan(request):
    return render(request, 'core/Personalloan.html')

def emergency_loan(request):
    return render(request, 'core/Emergencyloan.html')

loanapp/core/templates/core/partials/footer.html
<footer class="footer-one">
    <!-- Lower Footer -->
    <div class="container-fluid p-0">
        <div class="footer-lower">
            <div class="container">
                <div class="row row-gap-3">
                    <div class="col-md-6">
                        <div class="footer-copy-right-one">
                            <p>© <script>document.write(new Date().getFullYear())</script> StrategyiLoan. All rights reserved.</p>
                        </div>
                    </div>
                    <div class="col-md-6 text-center">
                        <div class="footer-buttom-link text-end">
                            <ul>
                                <li><a href="{% url 'terms' %}">Terms &amp; Conditions</a></li>
                                <li><a href="{% url 'privacy' %}">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div> <!-- /.row -->
            </div>
        </div>
    </div>
</footer>

loanapp/core/templates/core/partials/header.html
{% load static %}
<!-- Header Start -->
<header class="main-header main-header-four">
    <div class="container">
        <nav class="main-menu">
            <div class="main-menu-logo">
                <a href="{% url 'home' %}">
                    <img width="230px" src="{% static 'assets/images/logo.png' %}" alt="Strategy Loan logo">
                </a>
            </div>
            <div class="main-menu-inner">
                <ul class="main-menu-list">
                    <li class="menu-item-children"><a href="{% url 'services' %}">SERVICES</a></li>
                    <li class="menu-item-children"><a href="{% url 'terms' %}">TERMS</a></li>
                    <li class="menu-item-children"><a href="{% url 'privacy' %}">PRIVACY</a></li>
                    <li class="menu-item-children"><a href="{% url 'faq' %}">FAQ</a></li>
                </ul>
                <div class="header-right-end">
                    <span class="line-1"></span>
                    <span class="line-2"></span>
                    <span class="line-3"></span>
                </div>
            </div>
            <div class="main-menu-right d-flex align-items-center gap-2">
                <!-- Icon Buttons -->
                <a href="{% url 'user:login' %}" class="btn btn-icon" title="Login">
                    <i class="fas fa-user"></i>
                </a>
                <a href="{% url 'user:register' %}" class="btn btn-icon" title="Register">
                    <i class="fas fa-user-plus"></i>
                </a>
            </div>
        </nav>
    </div>
</header>